# Generated by Django 3.1.5 on 2021-01-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
