# Generated by Django 3.1.4 on 2021-01-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
