# Generated by Django 3.1.4 on 2021-01-09 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL)),
                ('user_following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
