# Generated by Django 3.1.4 on 2021-01-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinusers', '0004_auto_20210116_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
